### ISSUE TITLE
1. Go to "download" 2. Install Wallet. 3. Generate address. 4. Send coins. 5. coins stuck no connection. 6. rekt

### ISSUE THREAD

**Issue by NateCroix** [MustardWallet/MustardWalletLTC#10]
### Operating System

Please consider your privacy, before completing this section.  
Example: Ubuntu 16.04

### Logs

Please consider your privacy, before completing this section.  
You can find the log file by opening it from the main menu: `File/Open/Logs` File or `File/Open/TorLogs` File.

### Wasabi Version

Which wasabi release are you using? Where did you download it from?  
You can figure out which version you are using from the main menu: `Help/About` or with command line: `wassabee --version`.

**Comment by gabrielkrieger** [comment]
The backend had stopped running, restarted now, apologies for the downtime...!

**Comment by NateCroix** [comment]
> The backend had stopped running, restarted now, apologies for the downtime...!

No, this has not worked ONCE since I installed it weeks ago. Even now that the backend is connected I cannot send a transaction since it says "invalid fee rate", clicking "max" in the amount box results in "no coins selected" I cant figure out how to export private keys into something that works like electrum ltc as the format is completely different and there is basically zero documentation anywhere on how to troubleshoot these issues.

**Comment by gabrielkrieger** [comment]
The "no coins selected" error is because you have to select coins, using the check boxes next to your UTXO's , maybe that's the issue ? Please post a screenshot if possible .

As for Electrum LTC , you can restore your private keys from your seed words instead of doing the " export private keys " ...

**Comment by gabrielkrieger** [comment]
Nothing more to do , all systems up and running .
