### ISSUE TITLE
LTC lost with your software?

### ISSUE THREAD

**Issue by Micahellas1983** [MustardWallet/MustardWalletLTC#11]
Hello, I downloaded your software on Windows. Created Wallet address, sent ltc to the created wallet. Your software shows 0 balance, I cannot access these coins. Please help! Almost $200 is vanished. How can I get out my coins, please?

**Comment by nopara73** [comment]
I suspect you can use the LTC Electrum version, similarly to this guide: https://docs.wasabiwallet.io/using-wasabi/RestoreElectrum.html#restoring-wasabi-wallet-in-electrum

**Comment by Micahellas1983** [comment]
> I suspect you can use the LTC Electrum version, similarly to this guide: https://docs.wasabiwallet.io/using-wasabi/RestoreElectrum.html#restoring-wasabi-wallet-in-electrum

thank you so much, you saved my life :) <3

**Comment by gabrielkrieger** [comment]
The backend was down , it should work now ... I really need a beefier server to host this on ... apologies ...

**Comment by gabrielkrieger** [comment]
Is it working now for you ?

**Comment by gabrielkrieger** [comment]
After more than one month , no reply , so I guess it's good :)
