### ISSUE TITLE
Zero LTC price & error sending transactions

### ISSUE THREAD

**Issue by jslvn8871** [MustardWallet/MustardWalletLTC#16]
Backend is connected, but price is shown as Zero. As a result can't send any transactions - getting error message "Invalid fee rate" even if fee is manually set.
Also looks like status for confirmed transaction wasn't updated in the wallet

**Comment by sk4king** [comment]
same issue here :/

**Comment by gabrielkrieger** [comment]
Yeah , this time the litecoind process had stopped on the backend server . It's back now , thank you for reporting !
