### ISSUE TITLE
Send my ltc to my wallet but nothing

### ISSUE THREAD

**Issue by azuraservices** [MustardWallet/MustardWalletLTC#17]
I just send my ltc to a receive address generate after making a new wallet in mustard, i've tor connected and backend connected but 0 peers, my receive adress haven't a private key? How can i recover my funds?

**Comment by azuraservices** [comment]
Its stuck on connecting on the left corner.

**Comment by sk4king** [comment]
i think the backend is down again...

**Comment by gabrielkrieger** [comment]
Thanks for the report ! Indeed , this time it was litecoind that had stopped on the backend . I'm bringing it back up , should be ready to use in a few minutes ...

**Comment by sk4king** [comment]
> Thanks for the report ! Indeed , this time it was litecoind that had stopped on the backend . I'm bringing it back up , should be ready to use in a few minutes ...

thank you

**Comment by gabrielkrieger** [comment]
Looks good now !
