### ISSUE TITLE
Wallet does not recover with Key Phase

### ISSUE THREAD

**Issue by hashratez** [MustardWallet/MustardWalletLTC#7]
### General Description

I have installed the wallet on 3 machines:

1. Windows 10 PC -- original installation. Generated keyphase for backup. Sent 1 LTC to the wallet as a test. You can see the balance here: https://live.blockcypher.com/ltc/address/ltc1qjsmsmlh5rw70p523p27twj9p904pc24speu2cx/

2. Installed on Ubuntu 20.04 and proceeded to "recover" wallet.  The wallet recovers but there is no LTC.  The PVT and PUB keys are identical.  But the wallet does not show any balance. 

3. Installed the wallet on a Windows 10 notebook, recovered.  Same issues.  No LTC in the wallet, yet the KEYS are the same.

### Operating System

Please consider your privacy, before completing this section.  
Example: Ubuntu 16.04

### Logs

Please consider your privacy, before completing this section.  
You can find the log file by opening it from the main menu: `File/Open/Logs` File or `File/Open/TorLogs` File.

### Wasabi Version

Which wasabi release are you using? Where did you download it from?  
You can figure out which version you are using from the main menu: `Help/About` or with command line: `wassabee --version`.

**Comment by gabrielkrieger** [comment]
Ow damn , I completely missed this ticket , my apologies :-/ I hope it worked out in the end ?

There was some downtime of the servers around November of last year , maybe the wallet was unable to connect to the backend and therefore did not load anything .

If you still have the issue, could you try moving away your the .MustardWalletLTC folder from your home directory ( or from AppData on Windows ) and try again to start from a clean slate ?

Thank you for reporting , apologies again for missing this one !

**Comment by gabrielkrieger** [comment]
Still no reply , assuming it's fine again :)
