### ISSUE TITLE
ltc sending problem

### ISSUE THREAD

**Issue by steamkey12** [MustardWallet/MustardWalletLTC#8]
### General Description

i cant send any ltc why ? main network is down ? cuz i cant access onion web site also mustardwallet.com ?

### Screenshots

![image](https://user-images.githubusercontent.com/77557290/107120303-e5d49300-689d-11eb-87b7-5a92c8e8e0ed.png)

### Operating System

wi 10 x64 

### Wasabi Version
0.1.7

**Comment by gabrielkrieger** [comment]
Thank you for reporting ! The backend had crashed , I restarted it now and will keep an eye on it ! Everything good now on your end ?

**Comment by steamkey12** [comment]
> Bildirdiğiniz için teşekkürler! Arka uç çöktü, şimdi yeniden başlattım ve bir göz atacağım! Şimdi her şey yolunda mı?

Everything's working perfectly right now, thank you
